version: "3"
services:

  database:
    image: mysql:5.6
    container_name: database
    restart: always
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - wpnetwork
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    restart: always
    volumes:
      - wp-vol:/var/www/html
    depends_on:
      - database
    networks:
      - wpnetwork
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - wp-vol:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./example.com.crt:/var/ssl/example.com.crt
      - ./example.com.key:/var/ssl/example.com.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wpnetwork

volumes:
  wp-vol:
  db-vol:

networks:
  wpnetwork:
